### ISSUE TITLE
Unimplemented properties

### ISSUE THREAD

**Issue by JamesNK** [mikevalenty/faken#1]
Hi

I'm using your fake http objects and I've had to subclass them because not all of the properties are implemented.

There are probably many more but the ones I had to override to prevent NotImplementedExceptions are:

FakeHttpContext.Items
FakeHttpRequest.IsLocal

**Comment by mikevalenty** [comment]
I added implementations for HttpContext.Items and HttpRequest.IsLocal, I also added a few other missing ones while I was in there. There is an updated NuGet package available. Thanks for the feedback.

**Comment by JamesNK** [comment]
Thanks for making those changes. I've encountered some more that I've had to override to avoid errors:

FakeHttpRequest.ApplicationPath
FakeHttpResponse.ApplyAppPathModifier(string virtualPath)

**Comment by mikevalenty** [comment]
I added those too and a few more. There is an updated NuGet package available. Thanks again for the feedback and feel free to contribute!
